<a href="https://colab.research.google.com/github/johnsonAyo/imdb_dataset_analysis/blob/main/Movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive')
df = pd.read_csv('gdrive/My Drive/ML/Movies DB/movie_dataset_utf8.csv')
df.head()

Mounted at /content/gdrive

<ipython-input-1-c3b43faffcf8>:5: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('gdrive/My Drive/ML/Movies DB/movie_dataset_utf8.csv')

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,budget,...,original_title,overview,popularity,tagline,genres,production_companies,production_countries,spoken_languages,casts,director
0,27205,Inception,8.364,34495,Released,15/07/2010,825532764,148,False,160000000,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","Leonardo DiCaprio (Dom Cobb), Joseph Gordon-Le...",Christopher Nolan
1,157336,Interstellar,8.417,32571,Released,05/11/2014,701729206,169,False,165000000,...,Interstellar,The adventures of a group of explorers who mak...,140.241,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"Matthew McConaughey (Cooper), Anne Hathaway (B...",Christopher Nolan
2,155,The Dark Knight,8.512,30619,Released,16/07/2008,1004558444,152,False,185000000,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","Christian Bale (Bruce Wayne / Batman), Michael...",Christopher Nolan
3,19995,Avatar,7.573,29815,Released,15/12/2009,2923706026,162,False,237000000,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","Sam Worthington (Jake Sully), Zoe Salda√ía (Ney...",James Cameron
4,24428,The Avengers,7.710,29166,Released,25/04/2012,1518815515,143,False,220000000,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","Robert Downey Jr. (Tony Stark/Iron Man), Chris...",Joss Whedon

In [ ]:
#checking the data types
df.dtypes

id                        int64
title                    object
vote_average            float64
vote_count                int64
status                   object
release_date             object
revenue                   int64
runtime                   int64
adult                      bool
backdrop_path            object
budget                    int64
homepage                 object
imdb_id                  object
original_language        object
original_title           object
overview                 object
popularity              float64
poster_path              object
tagline                  object
genres                   object
production_companies     object
production_countries     object
spoken_languages         object
dtype: object

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 934745 entries, 0 to 934744
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    934745 non-null  int64
 1   title                 934734 non-null  object
 2   vote_average          934745 non-null  float64
 3   vote_count            934745 non-null  int64
 4   status                934745 non-null  object
 5   release_date          850217 non-null  object
 6   revenue               934745 non-null  int64
 7   runtime               934745 non-null  int64
 8   adult                 934745 non-null  bool
 9   budget                934745 non-null  int64
 10  homepage              101905 non-null  object
 11  imdb_id               552498 non-null  object
 12  original_language     934745 non-null  object
 13  original_title        934734 non-null  object
 14  overview              772348 non-null  object
 15  popularity            934745 non-null  float64
 16  tagline               136056 non-null  object
 17  genres                605754 non-null  object
 18  production_companies  456874 non-null  object
 19  production_countries  572431 non-null  object
 20  spoken_languages      578052 non-null  object
 21  casts                 219 non-null     object
 22  director              219 non-null     object
dtypes: bool(1), float64(2), int64(5), object(15)
memory usage: 157.8+ MB
None

In [ ]:
print(df.describe())

                 id   vote_average     vote_count       revenue  \
count  9.347450e+05  934745.000000  934745.000000  9.347450e+05
mean   6.223389e+05       2.232957      22.939624  7.782203e+05
std    3.331466e+05       3.152949     351.094674  1.798041e+07
min    2.000000e+00       0.000000       0.000000 -1.200000e+01
25%    3.509120e+05       0.000000       0.000000  0.000000e+00
50%    6.251880e+05       0.000000       0.000000  0.000000e+00
75%    9.122350e+05       5.294000       1.000000  0.000000e+00
max    1.185198e+06      10.000000   34495.000000  2.923706e+09

             runtime        budget     popularity
count  934745.000000  9.347450e+05  934745.000000
mean       51.889123  3.061706e+05       1.424210
std        62.425681  5.058921e+06       8.349914
min         0.000000  0.000000e+00       0.000000
25%         2.000000  0.000000e+00       0.600000
50%        39.000000  0.000000e+00       0.600000
75%        90.000000  0.000000e+00       0.958000
max     14400.000000  8.880000e+08    2994.357000

In [ ]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'budget', 'homepage', 'imdb_id',
       'original_language', 'original_title', 'overview', 'popularity',
       'tagline', 'genres', 'production_companies', 'production_countries',
       'spoken_languages', 'casts', 'director'],
      dtype='object')

In [ ]:
df.isnull().sum().sum()

5655644

In [ ]:
# Drop rows where 'title' column is missing
drop_missing_titles = df.dropna(subset=['title'])
drop_missing_titles.isnull().sum()

id                           0
title                        0
vote_average                 0
vote_count                   0
status                       0
release_date             84521
revenue                      0
runtime                      0
adult                        0
backdrop_path           659245
budget                       0
homepage                832829
imdb_id                 382236
original_language            0
original_title               0
overview                162389
popularity                   0
poster_path             239961
tagline                 798678
genres                  328985
production_companies    477860
production_countries    362306
spoken_languages        356685
dtype: int64

In [ ]:
drop_missing_titles.shape

(934734, 23)

In [ ]:
# sum rows where 'title' column is duplicated
df.duplicated('title').sum()

126982

In [ ]:
# drop rows where 'id' column is duplicated
df_missing_title_dup = df.drop_duplicates('id');
df_missing_title_dup.duplicated('id').sum()

0

In [ ]:
df_missing_title_dup.shape

(807762, 23)

In [ ]:
df_missing_title_dup.isnull().sum().sum()

4059430

In [ ]:
#replace all missing data with 0
replace_empty_values_with_null = df_missing_title_dup.fillna(value = 'null')

In [ ]:
replace_empty_values_with_null.isnull().sum().sum()

0

In [ ]:
replace_empty_values_with_null.shape

(807762, 23)

In [ ]:
replace_empty_values_with_null

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_language,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages
0,27205,Inception,8.364,34495,Released,15/07/2010,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,en,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili"
1,157336,Interstellar,8.417,32571,Released,05/11/2014,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,en,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English
2,155,The Dark Knight,8.512,30619,Released,16/07/2008,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin"
3,19995,Avatar,7.573,29815,Released,15/12/2009,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish"
4,24428,The Avengers,7.710,29166,Released,25/04/2012,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,en,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934736,657044,The Phantom Bullet,0.000,0,Released,09/05/1926,0,60,False,null,...,en,The Phantom Bullet,When Click's father is killed by a phantom bul...,0.613,/kYvKXxKwFhsuAxjD3HgJSSDaB9Y.jpg,null,Western,Universal Pictures,United States of America,No Language
934738,657048,Untitled 1985,0.000,0,Released,01/01/1985,0,6,False,null,...,en,Untitled 1985,"Originally filmed on standard 8mm Kodachrome, ...",0.600,/8GPnP8sWF1CcGfa7peKcmPCJBE6.jpg,null,null,null,null,null
934740,657051,M√∫sica √† moda do Porto,0.000,0,Released,01/01/2013,0,18,False,null,...,pt,M√∫sica √† moda do Porto,"Documentary about music of Porto, featuring a ...",0.600,null,null,Documentary,null,null,Portuguese
934742,657053,Terra M√£e,0.000,0,Released,01/01/2015,0,28,False,null,...,pt,Terra M√£e,The everyday paths are the reflex of who we ar...,0.600,/qYs4EVSpdU47a4mxeqL4LLqSfKo.jpg,null,Documentary,null,Portugal,Portuguese
934744,657037,Meeting My Daughter,0.000,0,Released,15/11/2001,0,0,False,null,...,en,Meeting My Daughter,"After a one-night stand, the director is told ...",0.600,null,null,null,null,null,null

In [ ]:
# Assuming your DataFrame is named df and the column name is 'description'
# Escape double quotes within the 'description' column
df.shape



# Reset the index if you want the index labels to be consecutive integers

(807761, 23)

In [ ]:
replace_empty_values_with_null.to_csv('/content/drive/My Drive/ML/moviesDB.csv', index=False)